repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.4.0
        hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files
        -   id: check-ast
        -   id: check-toml
        -   id: debug-statements

    -   repo: local
        hooks:
        -   id: ruff
            name: ruff check
            entry: ruff check --fix --exit-non-zero-on-fix
            language: system
            types: [python]

        -   id: ruff-format
            name: ruff format
            entry: ruff format
            language: system
            types: [python]

        -   id: pyright
            name: pyright
            entry: pyright
            language: system
            types: [python]
            pass_filenames: false

        -   id: pytest
            name: pytest
            entry: pytest
            language: system
            types: [python]
            pass_filenames: false

        -   id: codespell
            name: codespell
            entry: codespell
            language: system
            types: [text]
